-- Supabase schema for MIK ZID Villa booking system

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text,
  guests int,
  checkin date not null,
  checkout date not null,
  message text,
  preferred_contact text,
  status text not null default 'inquiry', -- inquiry | confirmed | blocked | cancelled
  payment_method text not null default 'pay_later', -- pay_later | pay_online
  payment_status text not null default 'unpaid', -- unpaid | paid | failed
  amount_lkr numeric(12,2) default 0,
  payhere_order_id text,
  payhere_payment_id text,
  source text default 'website'
);

create index if not exists bookings_dates_idx on public.bookings (checkin, checkout);
create index if not exists bookings_status_idx on public.bookings (status);
create index if not exists bookings_payhere_order_idx on public.bookings (payhere_order_id);
